@startuml

    abstract class Route {
        - name: String
        - routeFile: String

        + Route(name: String, routeFile: String)
        + printSummary(): void
    }

    class HikingRoute extends Route{
        - location: String 
        - timeToComplete: Duration
        - distance: double
        - difficulty: String
        - rating: double
        - description: String 
        - images: List<String>
        - keyPoints: List<String>

        + HikingRoute(name: String, location: String, distance: double, routeFile: String)
        + printSummary(): void
    }

@enduml